export const creativeData = {
    graphic: [
      { imgSrc: "/creative/csc-atlassian.svg",},
      { imgSrc: "/creative/csc-elections.svg"},
      { imgSrc: "/creative/csc-tesla.svg"},
      { imgSrc: "/creative/csc-bingo.svg"},
      { imgSrc: "/creative/csc-stripe.svg"},
      { imgSrc: "/creative/csc-eot.svg"},
    ],
    product: [
      { imgSrc: "/creative/ch-trophies.svg", description: "3D glass trophy models created in Blender for Chess Hacks."},
      { imgSrc: "/creative/ch-website.svg", description: "Chess Hacks website design including wireframes, visual design, and UX structure."},
      { imgSrc: "/creative/ch-stickers.svg", description: "Sticker designs for Chess Hacks, created in Procreate and Figma.",},
      { imgSrc: "/creative/ch-shirts.png", description: "Graphic T-shirts designed for Chess Hacks."},
      { imgSrc: "/creative/ch-badges.svg", description: "Hacker badges for Chess Hacks using Procreate and Figma."},
    ],
   illustration: [
        { imgSrc: "/creative/sketch-1.webp"},
        { imgSrc: "/creative/sketch-2.webp"},
        { imgSrc: "/creative/sketch-3.webp"},
        { imgSrc: "/creative/dg-1.webp"},
        { imgSrc: "/creative/sketch-4.webp"},
        { imgSrc: "/creative/sketch-5.webp"},
        { imgSrc: "/creative/sketch-6.webp"},
        { imgSrc: "/creative/dg-2.webp"},
        { imgSrc: "/creative/sketch-7.webp"},
        { imgSrc: "/creative/sketch-8.webp"},
        { imgSrc: "/creative/sketch-9.webp"},
        { imgSrc: "/creative/dg-3.webp"},
        { imgSrc: "/creative/sketch-10.webp"},
    ],
  };
