export const creativeData = {
    graphic: [
      { imgSrc: "/creative/csc-atlassian.webp",},
      { imgSrc: "/creative/csc-elections.webp"},
      { imgSrc: "/creative/csc-tesla.webp"},
      { imgSrc: "/creative/csc-bingo.webp"},
      { imgSrc: "/creative/csc-stripe.webp"},
      { imgSrc: "/creative/csc-eot.webp"},
    ],
    product: [
      { imgSrc: "/creative/ch-trophies.webp", description: "3D glass trophy models created in Blender for Chess Hacks."},
      { imgSrc: "/creative/ch-website.webp", description: "Chess Hacks website design including wireframes, visual design, and UX structure."},
      { imgSrc: "/creative/ch-stickers.webp", description: "Sticker designs for Chess Hacks, created in Procreate and Figma.",},
      { imgSrc: "/creative/ch-shirts.webp", description: "Graphic T-shirts designed for Chess Hacks."},
      { imgSrc: "/creative/ch-badges.webp", description: "Hacker badges for Chess Hacks using Procreate and Figma."},
    ],
   sketchbook: [
        { imgSrc: "/creative/sketch-1.webp"},
        { imgSrc: "/creative/sketch-2.webp"},
        { imgSrc: "/creative/sketch-3.webp"},
        { imgSrc: "/creative/dg-1.webp"},
        { imgSrc: "/creative/sketch-4.webp"},
        { imgSrc: "/creative/sketch-5.webp"},
        { imgSrc: "/creative/sketch-6.webp"},
        { imgSrc: "/creative/dg-2.webp"},
        { imgSrc: "/creative/sketch-7.webp"},
        { imgSrc: "/creative/sketch-8.webp"},
        { imgSrc: "/creative/sketch-9.webp"},
        { imgSrc: "/creative/dg-3.webp"},
        { imgSrc: "/creative/sketch-10.webp"},
    ],
  };
