export const projectsData = [
  {
    date: "02/25/2025",
    purpose: "Hack Canada 2025",
    title: "The Riffler",
    description: "Arduino powered self playing guitar",
    tags: ["Python", "C++", "CAD"],
    url: "riffler",
    imageUrl: "/projects/riffler.svg",
    link: "https://github.com/claireleu/The-Riffler",
  },
  {
    date: "27/09/2025",
    purpose: "Technova 2025",
    title: "Fashionkilla",
    description: "Smart closet: semantic outfit creation using vector databases, best use of MongoDB and best UI/UX at Technova 2025",
    tags: ["Next.js", "Python", "Pytorch", "MongoDB", "Typescript", "FastAPI"],
    url: "fashionkilla",
    imageUrl: "/projects/fashionkilla.svg",
    link: "https://youtu.be/nkZHyuDhQg0",
  },
  {
    date: "Sep 2025",
    purpose: "Hack the North 2025",
    title: "Rouvia",
    description: "Voice to text map agent for seamless hands-free route planning",
    tags: ["Python", "React", "Docker"],
    url: "rouvia",
  },
];
